name: Sync labels
on:
  issues:
    types: [opened, edited, deleted, labeled, closed]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download labels.yml
        run: curl -O https://raw.githubusercontent.com/micronaut-projects/micronaut-build/master/labels.yml
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          manifest: labels.yml